# -*- coding: utf-8 -*-
"""Week4_Day2Daily.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DmvgOvClhPmJ6DnBW54ciPB4bAnkFzBy
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**Data Import and Cleaning**"""

power_plant = pd.read_csv('/content/global_power_plant_database.csv')
power_plant.head()

print("Dataset Shape:", power_plant.shape)
print("\nColumn Names:")
print(power_plant.columns.tolist())

power_plant.info()

power_plant.describe()

print("Duplicate rows:", power_plant.duplicated().sum())

threshold = len(power_plant) * 0.7
print(threshold)

power_plant.isnull().sum()

threshold = len(power_plant) * 0.7
power_plant = power_plant.dropna(thresh=threshold, axis=1)

power_plant["capacity_mw"] = power_plant["capacity_mw"].fillna(power_plant["capacity_mw"].median())

power_plant["primary_fuel"] = power_plant["primary_fuel"].fillna("Unknown")

power_plant = power_plant.dropna(subset=["capacity_mw", "latitude", "longitude"])

gen_cols = [col for col in power_plant.columns if "generation_gwh" in col]

power_plant[gen_cols] = power_plant[gen_cols].fillna(0)

dpower_plant = power_plant.drop(columns=["url", "gppd_idnr", "wepp_id"], errors="ignore")

dpower_plant.isnull().sum().sort_values(ascending=False)

power_plant = power_plant.dropna(subset=["geolocation_source", "source"])

power_plant.isnull().sum()

power_plant.head()

power_plant.info()

# make sure DataFrame is called df
numeric_cols = ["capacity_mw", "latitude", "longitude", "estimated_generation_gwh_2017"]

# convert using np.array and astype
for col in numeric_cols:
    power_plant[col] = np.array(power_plant[col]).astype(float)

# verify
print(power_plant[numeric_cols].dtypes)

"""**Exploratory Data Analysis**"""

summary_stats = pd.DataFrame({
    "mean": power_plant[numeric_cols].mean(),
    "median": power_plant[numeric_cols].median(),
    "std": power_plant[numeric_cols].std()
})

print(summary_stats)

power_plant[numeric_cols].describe()

# count of power plants per country
country_counts = power_plant['country_long'].value_counts()
print(country_counts.head(10))  # top 10 countries

plt.figure(figsize=(12,6))
sns.barplot(x=country_counts.index[:10], y=country_counts.values[:10], palette='viridis')
plt.xticks(rotation=45)
plt.title("Top 10 Countries by Number of Power Plants")
plt.xlabel("Country")
plt.ylabel("Number of Power Plants")
plt.show()

# count of power plants per primary fuel
fuel_counts = power_plant['primary_fuel'].value_counts()
print(fuel_counts)

plt.figure(figsize=(10,5))
sns.barplot(x=fuel_counts.index, y=fuel_counts.values, palette='coolwarm')
plt.xticks(rotation=45)
plt.title("Distribution of Power Plants by Primary Fuel")
plt.xlabel("Primary Fuel")
plt.ylabel("Number of Power Plants")
plt.show()

# create a pivot table
country_fuel = power_plant.pivot_table(index='country_long', columns='primary_fuel',
                              values='name', aggfunc='count', fill_value=0)

# display top 10 countries by total plants
top_countries = country_counts.index[:10]
country_fuel_top = country_fuel.loc[top_countries]

print(country_fuel_top)

plt.figure(figsize=(12,6))
sns.heatmap(country_fuel_top, annot=True, fmt="d", cmap="YlGnBu")
plt.title("Number of Power Plants by Country and Fuel Type (Top 10 Countries)")
plt.xlabel("Fuel Type")
plt.ylabel("Country")
plt.show()

"""**Statistical Analysis**"""

fuel_types = power_plant['primary_fuel'].unique()
print(fuel_types)

stats = {}

for fuel in fuel_types:
    fuel_data = power_plant.loc[power_plant['primary_fuel'] == fuel, 'capacity_mw'].to_numpy()

    stats[fuel] = {
        'mean': np.mean(fuel_data),
        'median': np.median(fuel_data),
        'std': np.std(fuel_data, ddof=1),  # sample std
        'min': np.min(fuel_data),
        'max': np.max(fuel_data)
    }

# Convert to DataFrame for readability
stats_df = pd.DataFrame(stats).T
print(stats_df)

plt.figure(figsize=(10,6))
sns.boxplot(x='primary_fuel', y='capacity_mw', data=power_plant)
plt.xticks(rotation=45)
plt.title("Distribution of Power Plant Capacity by Fuel Type")
plt.ylabel("Capacity (MW)")
plt.xlabel("Primary Fuel")
plt.show()

from scipy.stats import f_oneway

# list of fuel types
fuel_types = power_plant['primary_fuel'].unique()

# collect capacity data for each fuel type
fuel_capacity_data = [power_plant.loc[power_plant['primary_fuel'] == fuel, 'capacity_mw'].to_numpy() for fuel in fuel_types]

# perform ANOVA
f_stat, p_value = f_oneway(*fuel_capacity_data)

print("F-statistic:", f_stat)
print("p-value:", p_value)

if p_value < 0.05:
    print("Significant difference in mean capacity among fuel types (reject H0).")
else:
    print("No significant difference in mean capacity among fuel types (fail to reject H0).")

"""**Advanced Visualization**"""

from urllib.request import urlopen
import geopandas as gpd
import folium
import json

with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

data_plant_copy = power_plant.copy()

data_plant_copy['latitude'] = pd.to_numeric(data_plant_copy['latitude'], errors='coerce')
data_plant_copy['longitude'] = pd.to_numeric(data_plant_copy['longitude'], errors='coerce')

fuel_color_map = {
    'Hydro': 'blue',
    'Solar': 'yellow',
    'Gas': 'orange',
    'Other': 'gray',
    'Oil': 'black',
    'Wind': 'green',
    'Nuclear': 'red',
    'Coal': 'brown',
    'Waste': 'purple',
    'Biomass': 'olive',
    'Wave and Tidal': 'cyan',
    'Petcoke': 'pink',
    'Geothermal': 'magenta',
    'Storage': 'lime',
    'Cogeneration': 'teal'
}


map_usa = folium.Map(location=[37.0902, -95.7129], zoom_start=4)

for index, row in data_plant_copy.iterrows():
    fuel_type = row['primary_fuel']
    fuel_color = fuel_color_map.get(fuel_type, 'gray')
    folium.CircleMarker(location=[row['latitude'], row['longitude']],
                        color=fuel_color,
                        fill=True,
                        fill_color=fuel_color).add_to(map_usa)

map_usa

import plotly.express as px

fuel_freq = power_plant.groupby(['country_long', 'primary_fuel']).size().reset_index(name='Frequency')

top_countries = fuel_freq.groupby('country_long')['Frequency'].sum().nlargest(10).index

fuel_freq_top = fuel_freq[fuel_freq['country_long'].isin(top_countries)]

fig = px.bar(fuel_freq_top, x='country_long', y='Frequency', color='primary_fuel',
             title='Frequency of Primary Fuel by Top 10 Countries',
             labels={'Frequency': 'Frequency', 'country_long': 'Country', 'primary_fuel': 'Primary Fuel'})
fig.show()

"""**Matrix Operations in Real-World Context**"""

numeric_columns = power_plant.select_dtypes(include=['int', 'float64'])
fig = px.imshow((numeric_columns.corr()).round(2), text_auto=True, aspect="auto")
fig.update_layout(title='Heatmap of Correlation', width=1200, height=800)
fig.show()
# count variance
numeric_columns.var()

"""**Integrating NumPy with Pandas and Matplotlib**"""

# Complex filter using NumPy
condition = (np.array(power_plant['capacity_mw']) > 50) & \
            (np.isin(power_plant['primary_fuel'], ['Hydro','Solar'])) & \
            (np.array(power_plant['latitude']) > 30)

filtered_df = power_plant[condition]
print(filtered_df)

# Encode fuel types numerically
fuel_map = {"Hydro":0, "Solar":1, "Gas":2, "Other":3, "Oil":4, "Wind":5, "Nuclear":6,
            "Coal":7, "Waste": 8, "Biomass":9, "Wave and Tidal":10, "Petcoke":11,
            "Geothermal":12, "Storage":13, "Cogeneration":14}
fuel_numeric = np.array([fuel_map[f] for f in power_plant['primary_fuel']])

# Add jitter to separate points with same fuel type
jitter = np.random.normal(0, 0.05, size=fuel_numeric.shape)
fuel_jittered = fuel_numeric + jitter

# Plot scatter of capacity vs fuel
plt.figure(figsize=(8,5))
plt.scatter(fuel_jittered, power_plant['capacity_mw'], alpha=0.7)
plt.xticks(list(fuel_map.values()), list(fuel_map.keys()), rotation=45)
plt.ylabel("Capacity (MW)")
plt.title("Power Plant Capacity by Fuel Type (with Jitter)")
plt.grid(True)
plt.show()

"""Report

Looking through the data we can see that the in the 2013 year Venezuela had the highest generation in gwh, while the United States had the lowest, in 2014 - the picture is changing and the highest generation and the lowest is in USA, which was really surprisingly, and we can see the same situation in 2016 and 2019. Through other years the USA stays with lowest valuues and the highest was in: 2015, 2017 - France, 2018 - India. Concerning the estimated Generation for all years China consistently had the highest estimated generation, while the United States varied but consistently appeared among the top countries.

We can see that the top 10 countries with high frequency by primary fuel of plants is: USA, United Kingdom, China, Brazil, Canada, France, Germany, India, Spain and Russia.

The most frequent primary fuel is Solar, Hydro and Wind.
"""